### ISSUE TITLE
Localized format is not translated beside 'en'

### ISSUE THREAD

**Issue by ctzuchiang** [kshetline/tubular_time#19]
## Expected Behavior

```
ttime().format('MMMM YYYY', 'zh-tw')

=> 八月 2021 or 8月 2021
```
## Current Behavior
```
ttime().format('MMMM YYYY', 'zh-tw')

=> 8 2021
```

## Detailed Description

By using below is working good, but looking for a way to localize format as `'MMMM YYYY'`
```
ttime().toLocale('zh-tw').format('LLLL')

=> 2021年8月26日 星期四 下午4:55
```

**Comment by kshetline** [comment]
I see the problem. I'm using Intl.DateTimeFormat to extract internationalized forms for different date/time fields. When I request `new Intl.DateTimeFormat('zh-tw', { dateStyle: 'long' }).formatToParts(new Date())`, I get a result like this:

<img width="596" alt="image" src="https://user-images.githubusercontent.com/24473229/131227795-d7516c9f-0487-4fcb-901d-020d84a307c5.png">

...and I just pull out the `month` value. That works for most languages (especially the western European languages I'm most familiar with), because anything in the `literal` category is usually just punctuation, not something that would be part of the isolated form of the month.

I'll try to figure out something that handles cases like this. Thanks for the feedback! Hopefully I'll have a bug fix for you soon.

**Comment by kshetline** [comment]
Okay, I've already come up with a fix for your bug to ensure that "MMMM" -> _digits_ 月, such as 8月, and it looks like you consider "8月 2021" an acceptable result for the "MMMM YYYY" format.

But would "8月 2021年" be better? It will be harder to make that work as a generalized solution, but let me know if that would be a better result, and worth the effort, as well as adding 日 where appropriate.

I'll publish the first fix now as is, but also do a further improvement if it seems like a good idea.

**Comment by ctzuchiang** [comment]
> Okay, I've already come up with a fix for your bug to ensure that "MMMM" -> _digits_ 月, such as 8月, and it looks like you consider "8月 2021" an acceptable result for the "MMMM YYYY" format.
> 
> But would "8月 2021年" be better? It will be harder to make that work as a generalized solution, but let me know if that would be a better result, and worth the effort, as well as adding 日 where appropriate.
> 
> I'll publish the first fix now as is, but also do a further improvement if it seems like a good idea.

First of all,Thank you for your help.

Yes, I am trying to use `'MMMM YYYY'` for calendar title. It is good question if `'YYYY'` come with literal as `'2021 年'`, kind of subjective question.

I think it is better not add literal letter behind `'YYYY'`, because it might be different usage in different kind of language、caulture or design.

As looking in other date package provider, `'date-fns'` ([link](https://date-fns.org/v2.23.0/docs/format)), it provide format as `'yo'` or `'Mo'` . Maybe can consider add `'o'` or other letter beheind to contrl the literal.

**Comment by kshetline** [comment]
I've already got support for `Mo` and `Do` (not `Yo`), but they aren't good equivalents for this use, since they're used for "ordinals". In English, this would be something like "January 1st" or "March 12th".

I decided that 'MMMM' will always add 月 for Chinese and Japanese months, or 월 for Korean months. But you can also use `_` to indicate what's normally a blank space for most languages, but it will be replaced with the appropriate CJK (Chinese, Japanese, Korean) symbols as needed.

Perhaps this code from my unit tests will give you an idea of what I'm trying to do. Does this look good?

```
  it('should properly handle special CJK date formatting', function () {
    expect(new DateTime('2021-08').format('MMMM YYYY', 'zh-tw')).to.equal('8月 2021');
    expect(new DateTime('2021-08').format('MMMM_YYYY_', 'zh-tw')).to.equal('8月2021年');
    expect(new DateTime('2021-08').format('MMMM_YYYY_', 'zh-cn')).to.equal('八月2021年');
    expect(new DateTime('2021-08').format('M_YYYY_', 'zh-cn')).to.equal('8月2021年');
    expect(new DateTime('2021-08').format('MM_YYYY_', 'zh-cn')).to.equal('08月2021年');
    expect(new DateTime('-2021-08').format('MMMM_y_n', 'ko')).to.equal('8월 2022년 BC');
    expect(new DateTime('-2021-08').format('MMMM_y_n', 'zh-hk')).to.equal('8月2022年公元前');
    expect(new DateTime('2021-08-29').format('MMMM_YYYY_DD_', 'ja')).to.equal('8月2021年29日');
    expect(new DateTime('2021-08-29').format('MMMM_YYYY_DD_', 'ko')).to.equal('8월 2021년 29일');
    expect(new DateTime('2021-08-29').format('MMMM_YYYY_DD_', 'en')).to.equal('August 2021 29');
    expect(new DateTime('2021-08-29').format('MMMM_, YYYY_DD_', 'en')).to.equal('August, 2021 29');
    expect(parse('1/17/2022 1:22:33', 'MM_/DD_/YYYY_ H:m:s', 'UTC').toIsoString(19)).to.equal('2022-01-17T01:22:33');
  });
```

The underscore can be used for all of these: YYYY_, y_, M_ or MM_ (always uses digits), MMMM_ (might use digits or Chinese words, depending on locale), D_, and DD_.

**Comment by ctzuchiang** [comment]
> I've already got support for `Mo` and `Do` (not `Yo`), but they aren't good equivalents for this use, since they're used for "ordinals". In English, this would be something like "January 1st" or "March 12th".
> 
> I decided that 'MMMM' will always add 月 for Chinese and Japanese months, or 월 for Korean months. But you can also use `~` to indicate what's normally a blank space for most languages, but it will be replaced with the appropriate CJK (Chinese, Japanese, Korean) symbols as needed.
> 
> Perhaps this code from my unit tests will give you an idea of what I'm trying to do. Does this look good?
> 
> ```
>   it('should properly handle special CJK date formatting', function () {
>     expect(new DateTime('2021-08').format('MMMM YYYY', 'zh-tw')).to.equal('8月 2021');
>     expect(new DateTime('2021-08').format('MMMM~YYYY~', 'zh-tw')).to.equal('8月2021年');
>     expect(new DateTime('2021-08').format('MMMM~YYYY~', 'zh-cn')).to.equal('八月2021年');
>     expect(new DateTime('2021-08').format('M~YYYY~', 'zh-cn')).to.equal('8月2021年');
>     expect(new DateTime('2021-08').format('MM~YYYY~', 'zh-cn')).to.equal('08月2021年');
>     expect(new DateTime('-2021-08').format('MMMM~y~n', 'ko')).to.equal('8월 2022년 BC');
>     expect(new DateTime('-2021-08').format('MMMM~y~n', 'zh-hk')).to.equal('8月2022年公元前');
>     expect(new DateTime('2021-08-29').format('MMMM~YYYY~DD~', 'ja')).to.equal('8月2021年29日');
>     expect(new DateTime('2021-08-29').format('MMMM~YYYY~DD~', 'ko')).to.equal('8월 2021년 29일');
>     expect(new DateTime('2021-08-29').format('MMMM~YYYY~DD~', 'en')).to.equal('August 2021 29');
>     expect(new DateTime('2021-08-29').format('MMMM~, YYYY~DD~', 'en')).to.equal('August, 2021 29');
>     expect(parse('1/17/2022 1:22:33', 'MM~/DD~/YYYY~ H:m:s', 'UTC').toIsoString(19)).to.equal('2022-01-17T01:22:33');
>   });
> ```
> 
> The tilde can be used for all of these: YYYY~, y~, M~ or MM~ (always uses digits), MMMM~ (might use digits or Chinese words, depending on locale), D~, and DD~.

For `zh-tw` & `zh-cn` & `zh-hk` those Chinese languages, could be better if `MMMM` or `MMMM~` output with same format : 

```
new DateTime('2021-08').format('MMMM', 'zh-tw') => 8月
new DateTime('2021-08').format('MMMM', 'zh-cn') => 8月
new DateTime('2021-08').format('MMMM', 'zh-hk') => 8月
new DateTime('2021-08').format('MMMM~', 'zh-tw') => 八月
new DateTime('2021-08').format('MMMM~', 'zh-cn') => 八月
new DateTime('2021-08').format('MMMM~', 'zh-hk') => 八月
```

Test case change to

```
expect(new DateTime('2021-08').format('MMMM YYYY', 'zh-tw')).to.equal('8月 2021');
expect(new DateTime('2021-08').format('MMMM~YYYY~', 'zh-tw')).to.equal('8月2021年'); => 八月2021年
expect(new DateTime('2021-08').format('MMMM~YYYY~', 'zh-cn')).to.equal('八月2021年');
expect(new DateTime('-2021-08').format('MMMM~y~n', 'zh-hk')).to.equal('8月2022年公元前'); => 八月2022年公元前
```

I'm not familiar other languages, but it does looks good with `~`.
User can easily format as what they want to be. 😄

**Comment by kshetline** [comment]
These changes are ready now if you update to version 3.5.0.

**Comment by kshetline** [comment]
Already bumped up to version 3.5.1... I decided to include MMM~ and Y~ format tokens too.
